# Generated by Django 2.2.6 on 2022-11-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20221117_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
    ]
