# Generated by Django 2.2.6 on 2022-11-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20221117_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата изменения'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата изменения'),
        ),
    ]
